deployment:
  api:
    name: api
    image: elijah668/api
    version: 1.0.0
    container:
      port: 8000
  client:
    image: elijah668/client
    name: client
    version: 1.0.0
    container:
      port: 80
    theme: dark
  