apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          env:
            - name: API_PATH
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: API_PATH
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: API_PORT
            - name: MONGO_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGO_CONTAINER_NAME
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_DB_NAME
          image: elijah668/api:1.0.0
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8000

          # tty: true
          # stdin: true
          # command: ["/bin/sh"]
